### ISSUE TITLE
No such file or directory?

### ISSUE THREAD

**Issue by otdwoodruff** [Juniper/py-junos-netconify#28]
Hey there, excited to try out this tool, but I seem to be missing something.. any insight? 

<b>trusty ~ %</b> uname -a 
<code>Linux trusty 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux</code>

<b>trusty ~ %</b> python --version
<code>Python 2.7.6</code>

<b>trusty ~ %</b> sudo pip install -U junos-netconify
<code>Requirement already up-to-date: junos-netconify in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pyserial in /usr/local/lib/python2.7/dist-packages (from junos-netconify)
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from junos-netconify)
Cleaning up...</code>

<b>trusty ~ %</b> locate netconify
<code>/usr/local/bin/netconify</code>

<b>trusty ~ %</b>netconify -/dev/ttyUSB0 -b 9600 -f host.conf
<code>: No such file or directory</code>

<b>trusty ~ %</b> ls | grep host
<code>host.conf</code>

**Comment by shermdog** [comment]
I'm thinking this error is being thrown prior to the script actually executing.

Can you try: ```netconfiy --help``` and see if it prints the help message?

**Comment by otdwoodruff** [comment]
Thanks for the reply. Seems you're right..

<b>trusty ~ %</b> netconify --help
<code>: No such file or directory</code>


Ahh I think I got it. So, running it as python directly from the directory  lets the command run properly it seems.. py script not finding python..?

<b>trusty ~ %</b> cat /usr/local/bin/netconify 
#!/usr/bin/env python2.7
<code>import sys
from netconify.cmdo import *

nc = netconifyCmdo()
results = nc.run()

if results['failed'] is True:
    print results['errmsg']
    sys.exit(1)</code>
<b>trusty ~ %</b> which python
<code>/usr/bin/python</code>
<b>trusty ~ %</b> which python2.7
<code>/usr/bin/python2.7</code>


Any suggestions? Did I break somthing in the install maybe? 


Thanks again

**Comment by shermdog** [comment]
You didn't break anything.  That file should have standard ```#!/usr/bin/python```.

Try changing that and post back.

This library had a different focus prior to release.  It now is primarily focused on use with our Ansible modules.

**Comment by otdwoodruff** [comment]
@shermdog that did it! Thanks for the tip. All is well now (closing issue :) )

trusty ~ % cat /usr/local/bin/netconify
#!/usr/bin/python

import sys
from netconify.cmdo import *

nc = netconifyCmdo()
results = nc.run()

if results['failed'] is True:
    print results['errmsg']
    sys.exit(1)

trusty ~ % sudo netconify
TTY:login:connecting to TTY:/dev/ttyUSB0 ...
TTY:login:logging in ...
