### ISSUE TITLE
netconify fails with 15.1+ releases on MX (FreeBSD10 based releases)

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-netconify#33]
netconify fails on 15.1+ releases on MX. There appears to be multiple problems. Some of these problems include:

1) Root shell prompt is different.

2) Junos version output is different. See https://github.com/Juniper/py-junos-eznc/issues/388

3) Console login prompt is slightly different.

4) Something appears to be different with reboot/logout.

**Comment by vnitinv** [comment]
Closed via #35
