### ISSUE TITLE
Mixed Line endings

### ISSUE THREAD

**Issue by jNicker** [Juniper/py-junos-netconify#34]
**Mixed line endings in project**

Specifically the tools/netconify bash script fails with:
`-bash: /usr/local/bin/netconify: /usr/bin/python^M: bad interpreter: No such file or directory`
on ubuntu 14.04. When installed via pip.

Can be corrected by running `dos2unix` on the file.

suggest looking at:
https://help.github.com/articles/dealing-with-line-endings/

**Comment by jNicker** [comment]
Still not Fixed?

**Comment by dgarros** [comment]
I don't have the issue when installing from github
I think the issue is with the PIP package
Will try to find someone to fix that

**Comment by vnitinv** [comment]
Fixed via release 1.0.2
