### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by ejmmanning** [Juniper/py-junos-netconify#38]
I install the library when I try to run it ,I get the following error 
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'netconify': [Errno 2] No such file or directory

I am running  version python2.7.9 on a MAC 

Thank you

**Comment by dgarros** [comment]
Hi 

I noticed that the script is not using a shebang compatible with pyenv 
https://github.com/Juniper/py-junos-netconify/blob/master/tools/netconify

I would suggest to replace the first line with
``` 
#!/usr/bin/env python
```
I just created a pull request for it, please can you try 
https://github.com/Juniper/py-junos-netconify/pull/39

Thanks
Damien

**Comment by ejmmanning** [comment]
dgarros  Thank I tried that and it did not help 

I type this to verify the module was installed

NAME
    netconify

FILE
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/netconify/__init__.py

PACKAGE CONTENTS
    cmdo
    constants
    facts
    tty
    tty_netconf
    tty_serial
    tty_telnet

SUBMODULES
    C

DATA
    __author__ = 'Jeremy Schulman, @nwkautomaniac'
    __date__ = '2016-Feb-08'
    __version__ = '1.0.2'

VERSION
    1.0.2

DATE
    2016-Feb-08
:

**Comment by ejmmanning** [comment]
Hello Nitin

How do I fix this 

Ed

**Comment by dgarros** [comment]
It got closed automatically because nitin merged the pull request i
created. Sorry about that.
I understand that you resolved your issue so i guess we're good

Thanks
Damien

**Comment by vnitinv** [comment]
@ejmmanning First uninstall the netconify

```
pip uninstall junos-netconify
```

then retry installing the module. Share the full logs. Want to check at which location netconfiy binary got copied. In Mac we find different locations for Python. pip might be installing netconify at some different location and when you try netconify command it might get looked at different location (in your case its /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS

So from the installation log, if you see other location being used to copy netconify, do add the parent folder to PYTHONPATH environment.

**Comment by vnitinv** [comment]
As per @ejmmanning After upgrading his system python, this issue got resolved.
