### ISSUE TITLE
pypi junos-netconify package needs updating

### ISSUE THREAD

**Issue by networkfoo** [Juniper/py-junos-netconify#57]
The package for py-junos-netconify at https://pypi.python.org/pypi/junos-netconify/1.0.2 has the following code (specifically line 22) in facts.py:
<pre>
        # extract the version
        # First try the <junos-version> tag present in >= 15.1
        <b>swinfo = rsp.xpath('.//junos-version')[0].text</b>
        if not swinfo:
            # For < 15.1, get version from the "junos" package.
            pkginfo = rsp.xpath(
</pre>
and when run this gives me an error:
<pre>
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "list index out of range"}
</pre>
I have changed my local 'python2.7/site-packages/netconify/facts.py' file to represent the current code at line 22 and this now functions correctly for me.
<pre>
        # extract the version
        # First try the <junos-version> tag present in >= 15.1
        <b>swinfo = rsp.findtext('junos-version', default=None)</b>
        if not swinfo:
            # For < 15.1, get version from the "junos" package.
            pkginfo = rsp.xpath(
</pre>

kind regards,

**Comment by vnitinv** [comment]
Hi, netconify has been merged in PyEZ. For telnet and console connection please use PyEZ from now onwards. refer
https://github.com/Juniper/py-junos-eznc/releases/tag/2.0.0
